"""empty message

Revision ID: 27af051e51b7
Revises: 96eb28ed788c
Create Date: 2020-03-29 12:49:04.985010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27af051e51b7'
down_revision = '96eb28ed788c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('PhoneNumber', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Doctor')
    # ### end Alembic commands ###
